version: '3.1'

services:
  ecommerce-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - mysql-data:/var/lib/mysql

  ecommerce-redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mysql-data:
